###
# THE MAIN SETTINGS OF THE APPLICATION.
# NEVER SHARE OR PUBLISH AS IT CONTAINS PASSWORDS.
#
# INFO: copy to app.private.conf and use
###

server.address="http://localhost"
server.port="9000"
application.secret="@FICK08Jj8nk1L;Sx?fUNeEL`re7D`9[RnKwbQ?KrCQs:31xz/HU8oqros3f[r1f"

###
# Database: Mongodb
###
mongodb.hostname="localhost"
mongodb.app.username="anyplace"
mongodb.app.password=""
mongodb.port=27017
mongodb.database="anyplace"

###
# salt and pepper to encrypt user's passwords
###
password.salt="MX4RFCEW2pmZb0AH3lbRWywp"
password.pepper="Ul0fUkSecNFuElqbcI7qfW81"

###
# Filesystem:
#
# - Raw data:
#  + floorplans, radiomaps, crlb data
###
floorPlansRootDir = "floorplans"
radioMapRawDir="radiomaps_raw"
radioMapFrozenDir="radiomaps_frozen"
tilerRootDir="anyplace_tiler"
